demos:
	$(CC) -Wall -g -o demo_write ../List/List.c ../HT/HashTable.c Json.c DemoWrite.c
	$(CC) -Wall -g -o demo_read ../List/List.c ../HT/HashTable.c Json.c DemoRead.c

clean:
	rm -f demo_write demo_read